<?php $this->headTitle('About'); ?>

<section class="hero is-link">
    <div class="hero-body">
        <div class="container">
            <h1 class="title">
                Who am I?
            </h1>
            <h2 class="subtitle">
                Software developer by day, Explorer by night.
            </h2>
        </div>
    </div>
</section>

<div class="section">
    <div class="container is-max-desktop">
        <div class="columns">
            <div class="column is-4">
                <div class="card">
                    <div class="card-image">
                        <figure class="image is-3by4">
                            <img src="/images/me.jpg" alt="Sander Lissenburg">
                        </figure>
                    </div>
                    <div class="card-content">

                        <p class="title is-4">Sander Lissenburg</p>
                        <p class="subtitle is-6">35 years</p>

                        <div class="content">
                            <p>PHP and JS Software developer and engineer. Interested in "Every thing" Computer, Mathematics, Biology, Physics, History, Science Fiction, Films and Series. Father of a son.<p>
                            <a href="https://twitter.com/lissenburg" target="_blank">@lissenburg</a>.
                            <a href="https://www.php.net/" target="_blank">#php</a>
                            <a href="https://developer.mozilla.org/en-US/docs/Web/JavaScript" target="_blank">#js</a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="column is-8">
                <div class="content">
                    <p>As a general computer enthusiast, there are millions of subjects to explore, learn, and fiddle with. This fact is a great thing for an intellectual changeling day job and to have as a hobby. However more often than not I'm overwhelmed and discouraged by the sheer amount of things you can (and have to) learn to do something truly awesome. And then there are none computer related subjects I'm also interested in. 24 hours in a day are just not enough. I want to use this website to collect my thoughts, document my progress, and maybe help or inspire others.</p>
                    <p>Subjects I explore could have the same theme or could not be related at all. My interests can change by the day. It depends on what I read in a book, experience during a game, see in a movie or hear in a podcast. There is no goal, just a journey. We'll see where it goes or where I end up. I'll keep you posted...</p>
                </div>
            </div>
        </div>
    </div>
</div>
