<?php $this->headTitle('About'); ?>

<section class="hero is-link">
    <div class="hero-body">
        <div class="container">
            <h1 class="title">
                About me.
            </h1>
            <h2 class="subtitle">
                Software engineer by day, Software engineer by night
            </h2>
        </div>
    </div>
</section>

<div class="section">
    <div class="container is-max-desktop">
        <div class="columns">
            <div class="column is-4">
                <div class="card">
                    <div class="card-image">
                        <figure class="image is-3by4">
                            <img src="/images/me.jpg" alt="Sander Lissenburg">
                        </figure>
                    </div>
                    <div class="card-content">

                        <p class="title is-4">Sander Lissenburg</p>
                        <p class="subtitle is-6">35 jaar</p>

                        <div class="content">
                            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                            Phasellus nec iaculis mauris.<p>
                            <a>@lorem</a>.
                            <a href="#">#php</a>
                            <a href="#">#js</a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="column is-8">
                <div class="content">
                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc sed mi iaculis, tincidunt magna efficitur, hendrerit ante. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Aenean congue facilisis massa a consequat. Donec at mi et ipsum aliquam porta. Nullam accumsan ut sem blandit blandit. Nullam purus arcu, pellentesque eu efficitur ut, iaculis id turpis. Praesent viverra sodales metus. Integer vehicula dui et rutrum tincidunt. Cras vulputate augue pulvinar, fermentum nunc a, feugiat risus.</p>
                    <p>Nullam et eros a odio aliquet hendrerit ut id libero. Quisque eu pretium ante. Etiam luctus turpis in sagittis sagittis. Nullam vel libero ac ante sagittis posuere. Morbi ut blandit odio, blandit venenatis felis. Nunc nec commodo urna. In pellentesque, nulla non dignissim rhoncus, quam ipsum consequat turpis, vel semper nisl neque vitae ex. Quisque et nisi et mi convallis suscipit ut eget magna. Aliquam efficitur ante quam, ut dictum justo tincidunt sed. Donec interdum pretium ex ut viverra. Donec imperdiet tellus massa, id hendrerit nibh fermentum a. In eros sem, gravida a tempor non, pharetra in magna. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Mauris vitae lorem erat. Ut semper risus lacus, a laoreet odio eleifend sed.</p>
                </div>
            </div>
        </div>
    </div>
</div>
