<?php $this->headTitle('Archive'); ?>

<section class="hero is-link">
    <div class="hero-body">
        <div class="container">
            <h1 class="title">Archive.</h1>
        </div>
    </div>
</section>
<section class="section">
    <div class="container is-max-desktop">
        <?php foreach ($this->stories as $story): ?>
            <article class="pb-5">
                <h1 class="title is-4"><?= $this->escapeHtml($story->getTitle()) ?></h1>
                <h2 class="subtitle is-7 has-text-grey"><?= $story->getCreatedAt()->format('F j, Y') ?></h2>
                <div class="tags">
                    <?php foreach ($story->getTags() as $tag): ?>
                        <span class="tag is-info"><?= $this->escapeHtml($tag->getLabel()) ?></span>
                    <?php endforeach; ?>
                </div>
                <div class="content">
                    <?= $story->getIntro() ?>
                </div>
                <a href="<?= $this->url('story.detail', ['slug' => $story->getSlug()]) ?>">Read more</a>
            </article>
        <?php endforeach; ?>
    </div>
</section>
