<?php $this->headTitle('Home'); ?>

<section class="hero is-link">
    <div class="hero-body">
        <div class="container">
            <h1 class="title">
                Hello world!
            </h1>
            <h2 class="subtitle">
                Welcome to my exploration journal in the world of Computers.
            </h2>
        </div>
    </div>
</section>

<div class="section">
    <div class="container is-max-desktop">
        <div class="columns">
            <section class="column is-8">

                <h1 class="title is-5 has-text-grey">Long stories</h1>

                <?php foreach ($this->longStories as $story): ?>
                    <article class="pb-5">
                        <h1 class="title is-size-1"><?= $this->escapeHtml($story->getTitle()) ?></h1>
                        <h2 class="subtitle is-7 has-text-grey"><?= $story->getCreatedAt()->format('F j, Y') ?></h2>
                        <div class="tags">
                            <?php foreach ($story->getTags() as $tag): ?>
                            <span class="tag is-info"><?= $this->escapeHtml($tag->getLabel()) ?></span>
                            <?php endforeach; ?>
                        </div>
                        <div class="content is-size-4">
                            <?= $story->getIntro() ?>
                        </div>
                        <div class="content">
                            <?= \App\Application\Helper\TextTruncate::truncate($story->getContent(), 400) ?>
                        </div>
                        <a href="<?= $this->url('story.detail', ['slug' => $story->getSlug()]) ?>">Read more</a>
                    </article>
                <?php endforeach; ?>
            </section>

           <section class="column">

               <h1 class="title is-5 has-text-grey">About</h1>

               <article class="pb-6">
                   <div class="pb-4">
                       <figure class="image is-128x128">
                           <img class="is-rounded " src="/images/me-square.jpg" alt="Sander Lissenburg">
                       </figure>
                   </div>
                   <p class="title is-6">Sander Lissenburg</p>
                   <p class="subtitle is-7">35 years</p>
                   <p>PHP and JS software developer and engineer. Interested in "Every thing" Computer, Mathematics, Biology, Physics, History, Science Fiction, Gaming, Films and Series. Father of a son.<p>
               </article>

               <h2 class="title is-5 has-text-grey">Short stories</h2>

               <?php foreach ($this->shortStories as $story): ?>
                   <article class="pb-5">
                       <h1 class="title is-4"><?= $this->escapeHtml($story->getTitle()) ?></h1>
                       <h2 class="subtitle is-7 has-text-grey"><?= $story->getCreatedAt()->format('F j, Y') ?></h2>
                       <div class="tags">
                           <?php foreach ($story->getTags() as $tag): ?>
                               <span class="tag is-info"><?= $this->escapeHtml($tag->getLabel()) ?></span>
                           <?php endforeach; ?>
                       </div>
                       <div class="content">
                           <?= $story->getIntro() ?>
                       </div>
                       <a href="<?= $this->url('story.detail', ['slug' => $story->getSlug()]) ?>">Read more</a>
                   </article>
               <?php endforeach; ?>

           </section>
        </div>
    </div>
</div>

