name: Frontend deployment

on:
  push:
    branches:
      - master
    tags:
      - v1.*

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Pull image to create cache
        run: |
          docker pull lissenburg/website-frontend-nginx
      - name: Build image
        run: |
          make build-prod
      - name: Docker login
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_ID }}" --password-stdin
      - name: Push image
        run: |
          docker push lissenburg/website-frontend-nginx
      - name: Test ssh proxy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          proxy_host: ${{ secrets.SSH_PROXY_HOST }}
          proxy_username: ${{ secrets.SSH_PROXY_USER }}
          proxy_key: ${{ secrets.SSH_PRIVATE_KEY }}
          proxy_port: 22
          script: |
            docker stop lissenburg_website
            docker pull lissenburg/website-frontend-nginx
            docker run -d --rm -p 80:80 --name lissenburg_website lissenburg/website-frontend-nginx
