name: Frontend deployment

on:
  push:
    branches:
      - master
    tags:
      - v1.*

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Create ssh key
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H secrets.SSH_ENTRY_HOST >> ~/.ssh/known_hosts
      - name: Deploy with sh script
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_ID: ${{ secrets.DOCKER_ID }}
          SSH_ENTRY_HOST: ${{ secrets.SSH_ENTRY_HOST }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USER: ${{ secrets.SSH_USER }}
        run: sh deploy/deploy.sh
